"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # 项目基本目录的路径

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d5ui0x*xdbi038b!lc1era@*&c)sdg1#wy=)ou3w3he^&5=ci4'  # 用于加密的密钥，必须保持秘密

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # 开发模式的标志，生产环境中应设为 False

ALLOWED_HOSTS = []  # 允许访问的主机列表，生产环境中必须设置

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',  # Django 管理后台
    'django.contrib.auth',  # 用户认证
    'django.contrib.contenttypes',  # 内容类型框架
    'django.contrib.sessions',  # 会话框架
    'django.contrib.messages',  # 消息框架
    'django.contrib.staticfiles',  # 静态文件管理
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # 安全中间件
    'django.contrib.sessions.middleware.SessionMiddleware',  # 会话中间件
    'django.middleware.common.CommonMiddleware',  # 常见中间件
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF 保护中间件
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # 身份验证中间件
    'django.contrib.messages.middleware.MessageMiddleware',  # 消息中间件
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # 防止点击劫持中间件
]

ROOT_URLCONF = 'project.urls'  # 项目的根 URL 配置模块

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # 使用 Django 的模板引擎
        'DIRS': [],  # 自定义模板目录列表（可根据需要添加）
        'APP_DIRS': True,  # 是否在已安装应用的 templates 子目录中查找模板
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # 调试上下文处理器
                'django.template.context_processors.request',  # 请求上下文处理器
                'django.contrib.auth.context_processors.auth',  # 用户认证上下文处理器
                'django.contrib.messages.context_processors.messages',  # 消息上下文处理器
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'  # 指定 WSGI 应用程序的路径

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # 使用 SQLite 数据库
        'NAME': BASE_DIR / 'db.sqlite3',  # 数据库文件路径
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # 用户属性相似性验证器
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # 最小长度验证器
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # 常见密码验证器
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # 数字密码验证器
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'  # 默认语言代码

TIME_ZONE = 'UTC'  # 默认时区

USE_I18N = True  # 是否启用国际化

USE_TZ = True  # 是否启用时区支持

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'  # 静态文件的 URL 路径

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # 默认主键字段类型
