# Generated by Django 5.1.2 on 2024-11-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_device_device_id_remove_device_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_address', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=1883)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
