# Generated by Django 5.1.2 on 2024-11-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_mqttserverconfig_device_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicevariable',
            name='data_direction',
            field=models.CharField(choices=[('receive', 'Receive'), ('send', 'Send'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
