# Generated by Django 5.1.2 on 2024-11-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_devicevariable_data_direction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MQTTServerConfig',
            new_name='MqttServer',
        ),
    ]
